(function(){
  const STORAGE_KEY='budde.ocrDiagnostics.v1';
  const RETENTION_MS=90*24*60*60*1000;
  const textEncoder=new TextEncoder();
  function now(){return new Date().toISOString()}
  function load(){try{const value=localStorage.getItem(STORAGE_KEY);return value?JSON.parse(value):[]}catch(error){console.warn('Diagnostic OCR illisible.',error);return []}}
  function save(items){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
  function purge(items=load()){const min=Date.now()-RETENTION_MS;const kept=items.filter(item=>Date.parse(item.createdAt)>=min);if(kept.length!==items.length)save(kept);return kept}
  function byteLength(value){return new Blob([typeof value==='string'?value:JSON.stringify(value||{})]).size}
  function blobToDataUrl(blob){return new Promise(resolve=>{if(!blob){resolve(null);return}const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>resolve(null);reader.readAsDataURL(blob)})}
  function safeName(value){return String(value||'diagnostic').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'').toLowerCase()||'diagnostic'}
  function fileExt(blob,fallback='jpg'){const type=String(blob?.type||'').split('/').pop();return type&&type.length<8?type:fallback}
  async function create(payload={}){const items=purge();const createdAt=now();const id=`ocr-${createdAt.replace(/[:.]/g,'-')}-${Math.random().toString(36).slice(2,8)}`;const raw=payload.rawPhoto?await blobToDataUrl(payload.rawPhoto):null;const buddy=payload.buddyVisionImage?await blobToDataUrl(payload.buddyVisionImage):null;const record={id,createdAt,rawPhoto:raw?{name:payload.rawPhoto.name||'photo-brute',type:payload.rawPhoto.type||'image/jpeg',dataUrl:raw}:null,buddyVisionImage:buddy?{name:payload.buddyVisionImage.name||'buddy-vision',type:payload.buddyVisionImage.type||'image/jpeg',dataUrl:buddy}:null,rawOcr:payload.rawOcr||null,buddyResult:payload.buddyResult||null,userCorrections:payload.userCorrections||{},metadata:{appVersion:payload.appVersion||null,buildId:payload.buildId||null,userAgent:navigator.userAgent,createdAt,...(payload.metadata||{})}};items.push(record);save(purge(items));return record}
  function stats(){const items=purge();const sizes=items.map(byteLength);const total=sizes.reduce((a,b)=>a+b,0);const dates=items.map(item=>item.createdAt).sort();return {count:items.length,totalBytes:total,averageBytes:items.length?Math.round(total/items.length):0,oldest:dates[0]||null,newest:dates.at(-1)||null}}
  function clear(){save([])}
  function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  let crcTable=null;function crc32(bytes){crcTable=crcTable||Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0});let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
  function u16(n){return [n&255,(n>>>8)&255]}function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
  function zipDate(date){const d=new Date(date);return {time:(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()/2),date:((d.getFullYear()-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate()}}
  function dataUrlBytes(dataUrl){const b64=String(dataUrl||'').split(',')[1]||'';const bin=atob(b64);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
  function addJson(files,path,data){files.push({path,bytes:textEncoder.encode(JSON.stringify(data,null,2))})}
  function buildFiles(items){const files=[];items.forEach(item=>{const dir=`${safeName(item.createdAt)}-${safeName(item.id)}`;if(item.rawPhoto?.dataUrl)files.push({path:`${dir}/photo-brute.${fileExt(item.rawPhoto)}`,bytes:dataUrlBytes(item.rawPhoto.dataUrl)});if(item.buddyVisionImage?.dataUrl)files.push({path:`${dir}/image-buddy-vision.${fileExt(item.buddyVisionImage)}`,bytes:dataUrlBytes(item.buddyVisionImage.dataUrl)});addJson(files,`${dir}/ocr-brut.json`,item.rawOcr||{});addJson(files,`${dir}/resultat-buddy.json`,item.buddyResult||{});addJson(files,`${dir}/corrections-utilisateur.json`,item.userCorrections||{});addJson(files,`${dir}/metadonnees.json`,item.metadata||{});});return files}
  function makeZip(files){let offset=0;const local=[],central=[];for(const file of files){const name=textEncoder.encode(file.path),bytes=file.bytes,crc=crc32(bytes),dt=zipDate(new Date());local.push(Uint8Array.from([0x50,0x4b,3,4,...u16(20),0,0,0,0,...u16(dt.time),...u16(dt.date),...u32(crc),...u32(bytes.length),...u32(bytes.length),...u16(name.length),0,0,...name,...bytes]));central.push(Uint8Array.from([0x50,0x4b,1,2,...u16(20),...u16(20),0,0,0,0,...u16(dt.time),...u16(dt.date),...u32(crc),...u32(bytes.length),...u32(bytes.length),...u16(name.length),0,0,0,0,0,0,0,0,0,...u32(offset),...name]));offset+=local.at(-1).length}const centralSize=central.reduce((s,x)=>s+x.length,0);return new Blob([...local,...central,Uint8Array.from([0x50,0x4b,5,6,0,0,0,0,...u16(files.length),...u16(files.length),...u32(centralSize),...u32(offset),0,0])],{type:'application/zip'})}
  async function exportZip(){const items=purge();const blob=makeZip(buildFiles(items));downloadBlob(blob,`Budde-diagnostics-OCR-${new Date().toISOString().slice(0,10)}.zip`);return blob}
  window.OcrDiagnosticService={create,stats,clear,exportZip,purge};
})();
